### ISSUE TITLE
Missing information on how to handle API call error

### ISSUE THREAD

**Issue by BboyKeen** [Mangopay/mangopay2-php-sdk#133]
When looking at the documentation, a standard user could think that MangoPay API calls never fail.
However, if we dig into MangoPay failure history on http://status.mangopay.com/, we can see that sometimes the server is not reachable (IT is sometimes so surprising :D)

It could be a good enhancement to the documentation to add a few information on how we can deal with this kind of failure.
The information is already present in the test cases but I think you should put forward that the user must catch MangoPay\Libraries\Exception and MangoPay\Libraries\ResponseException to handle errors gracefully

I can issue a PR if you tell me exactly the right way to handle errors using the SDK.

**Comment by hobailey** [comment]
Hey @BboyKeen, thanks for the feedback :-)
I'm not quite sure what you have in mind by "gracefully" - do you mean just having simple try/catch/catch in these cases? If so, we would always suggest this approach (as per [here](https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/users_all.php) for example) rather than just a simple API call and crossing your fingers :-)

Apart from a try/catch, I'm not sure what you mean by the "right way" - could you give some more info please?

**Comment by BboyKeen** [comment]
Exactly, that's what I'm thinking of.

I couldn't find any information about until I dig into the tests. This is not a big concern for me but for less experienced users it could be useful to remind them that a API call can fail by try catching the examples given in the README.

**Comment by hobailey** [comment]
OK, well we'll update the readme, good point. Other than that, the demos included in the SDK, the tests, and the PHP example code on our documentation site all use try/catch so hopefully it's quite clear :-) But as you say, would be good to have in the readme too!

**Comment by BboyKeen** [comment]
Well, my bad.. I didn't even noticed the demos folder. Thanks.

Having it in readme too will make the library examples consistent :)
