### ISSUE TITLE
Change Mangopay client_id , passphrase or email  

### ISSUE THREAD

**Issue by anbwar** [Mangopay/mangopay2-php-sdk#135]
Hello , 

Can i change the mangopay Email or client id or the passphrase using mangopay APi,
is there a solution to change one of those parametres ?

Thanks

**Comment by hobailey** [comment]
Hi, you can't change the `ClientId` since this is a fundamental part of your account :-) 
At this time, you also can't change the `Passphrase` although we hope to add that next year. As for the `Email`, this you can do :-) Either via the [Dashboard](https://docs.mangopay.com/guide/dashboard), or via the [API/SDK directly](https://docs.mangopay.com/endpoints/v2.01/clients#e201_update-a-client).

**Comment by anbwar** [comment]
i want to change the app user email, not the client email !

**Comment by anbwar** [comment]
to connect to mangopay there is 
-client id
-Email
-passphres
i want to change this email

**Comment by hobailey** [comment]
If you want to change the email address for your client, as I previously said, here is the info how to do it: https://docs.mangopay.com/endpoints/v2.01/clients#e201_update-a-client

**Comment by anbwar** [comment]
I don't want to change the email adress for my client !
i want to change my email adress that i connect with on mangopay dashboard.

Thank you for your understanding

**Comment by hobailey** [comment]
Ah, OK - so nothing to do with the `Passphrase` :-)
Unfortunately it is not possible to change the `Email` at this time, but we'll be adding this functionality in the next few months :-)
