### ISSUE TITLE
Unmatching documentation on Users->CreateKycPageFromFile

### ISSUE THREAD

**Issue by fimdomeio** [Mangopay/mangopay2-php-sdk#189]
The code snippet on the documentation page at https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e208_create-a-kyc-page has the following line:
`Api->Users->CreateKycPageFromFile($UserId, $KYCDocumentId, $KycPage);`
Where KycPage is an Object instance of \MangoPay\KycPage

The example does not work.
The code that actually works is `Api->Users->CreateKycPageFromFile($UserId, $KYCDocumentId, $path)` where $path is a file path.

Also  this function as no return values on success which seems a little odd too me since everything else as a return response.

**Comment by mickaelpois** [comment]
Hi @fimdomeio,

Thanks for your feedback.
Our documentation site could be errored for that particular endpoint due to how we manage it today (it only reflects properties contained in a particular business object, and not technical aspects that could be useful for some endpoint like KYC one), and we hope we could provide an enhanced public documentation site very soon.

For return value purpose, our API returns no body response because we decided it was useless. As it is an upoad process, we just send back HTTP code which relfects upload state.

Let me see these two points in details and I will keep you posted about any update / decision that could help you in the future :)

Mickaël
