### ISSUE TITLE
GetKycDocument throws Warning: Creating default object from empty value

### ISSUE THREAD

**Issue by lbaey** [Mangopay/mangopay2-php-sdk#197]
The problem occur in RestTool.php ReadResponseHeader(), line 218
``` 
$this->_pagination->TotalPages = (int)trim(str_replace('X-Number-Of-Pages:', '', $header));
```
The _pagination property is null.
It is set only when GetList() is called for the Request. 
For GetKycDocument(), the GetObject() method is called instead although it returns a collection and the Pages header is set.

**Comment by paulhristea** [comment]
Hello @lbaey, sorry about the delay.

I'm looking at the code and I can see 2 methods matching your case: the `GetKycDocument()` and `GetKycDocuments()` methods from `ApiUsers`. If you are still having this issue, could you please confirm that you are not by mistake using the `GetKycDocument()` method (which returns only one document by id) instead of the `GetKycDocuments()` method (which returns a paginated list)? Or are we talking about a different method?

Thanks for your cooperation!
