### ISSUE TITLE
Encodage 64 Problem : (Message : File not exist)

### ISSUE THREAD

**Issue by airjobbing** [Mangopay/mangopay2-php-sdk#234]
Hello, 

I have a problem to encode the document uploaded by the user because code bellow display "Message : File not exist" exception.

$kycPage = new \MangoPay\KycPage();
$kycPage->File = base64_encode(file_get_contents($FILE['document']['tmp_name'])
$mangopayAPI->Users->CreateKycPageFromFile($idUser, $KycDocumentId, $kycPage);

Can you help me please ?

Thanks

**Comment by paulhristea** [comment]
Hello @airjobbing, thanks for reaching out.

Can you confirm the contents of the `$FILE['document']['tmp_name']` expression? As far as I know, usually the global variable `$_FILES` is used for getting files uploaded in a request. Maybe try it like that.
Please give us some more details about how you are trying to get the Base64 content, so we can figure out your problem here.

Thanks!

**Comment by MaxCodi** [comment]
Hello, I'm experiencing the same problem.

In the PHP Sdk in ApiUsers.php CreateKycPage function, it's checking the base64 document with file_exists().
So I've tried to send a file instead, but nothing is working.

So I'll join @airjobbing to wait if someone can help ;-)

Max

**Comment by MaxCodi** [comment]
so The API is returning a 204 error code "No content", but in fact, it's working. So if you want to have a better information, just add a return true; in the CreateKycPage function of ApiUsers.php

**Comment by mickaelpois** [comment]
THanks for your feedback @MaxCodi !
I guess it could be a good idea in fact, as it's a simple solution to let you know your upload is successful.

I'll keep you posted about a future PR and release around it.

Mickaël

**Comment by mickaelpois** [comment]
@MaxCodi Good news ! Our next release will contain #280, adding boolean return value for KYC docs upload, as requested 👍
