### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by Alexissarfati** [Mangopay/mangopay2-php-sdk#235]
Hi,

I try to user mango Transfer to send money from a wallet to another one
Here my code : 
        $Transfer = new \MangoPay\Transfer();
        $Transfer->DebitedWalletId = $_SESSION['user']['mango_wid'];
        $Transfer->CreditedWalletId = $user['mango_wid'];
        $Transfer->AuthorId = $_SESSION['user']['mango_uid'];
        $Transfer->Tag = "Commande #{$cid}";
        $Transfer->DebitedFunds = new \MangoPay\Money();
        $Transfer->DebitedFunds->Amount = ($vendeur*100);
        $Transfer->DebitedFunds->Currency = MPAY_CURRE;
        $Transfer->CreditedFunds = new \MangoPay\Money();
        $Transfer->CreditedFunds->Amount = ($vendeur*100);
        $Transfer->CreditedFunds->Currency = MPAY_CURRE;
        $Transfer->Fees = new \MangoPay\Money();
        $Transfer->Fees->Amount = 0;
        $transfert_result=$Transfer->Transfer->Create($Transfer);

But new \MangoPay\Transfer(); semme to not exist 

Can you please tell me how to solve it ?

Thanks

**Comment by iammichiel** [comment]
What is the error exactly ?

**Comment by paulhristea** [comment]
Hello @Alexissarfati!

Have you since been able to solve this issue? The syntax in your example code seems to be correct, just make sure you have followed the README.md installation instructions from https://github.com/Mangopay/mangopay2-php-sdk , and if the problem persists, please give us some more specific details as to the error you are encountering, or maybe some steps to reproduce it in order to debug locally.

Thanks!
