### ISSUE TITLE
"MangoPay\Exception Message: Cannot put token to file"

### ISSUE THREAD

**Issue by Manu2V** [Mangopay/mangopay2-php-sdk#236]
Hello,

Thans for your help, i have this problem on mangopay but i don't understand how i can resolve it in the code ?

in 
    $serialized = serialize($token);
    $result = file_put_contents($this->GetPathToFile(), $this->_prefixContent . $serialized, LOCK_EX);
    if ($result === false)
        throw new \MangoPay\Libraries\Exception('Cannot put token to file');
On my web site, sometimes it works sometimes the message "MangoPay\Exception Message: Cannot put token to file" appears and don't permit the payment via mangopay.

Can you help me please,

Manu

**Comment by paulhristea** [comment]
Hello @Manu2V!

Thanks for reaching out, and sorry about the delayed response.
Is there any chance that the `Store($token)` function is being called from multiple threads at the same time? At first sight, this could be the cause of your occasional problem, because we are writing to the file using the `LOCK_EX` flag, which means that the file gets locked while we are writing to it, so nobody else will be allowed to write at the same time. This is what might cause the `$result` value to be false.

Please get back to us with more details about how to reproduce this error if it is not the case.
Thank you!
