### ISSUE TITLE
MangoPay UpdateBankAccount (desactivate account bank)

### ISSUE THREAD

**Issue by ChristopherTRIERWEILER** [Mangopay/mangopay2-php-sdk#239]
I am developing under symfony and I am looking to disable a bank account by the api of MangoPay. It is necessary to use the method PUT but I have difficulty to understand how to do it correctly: 

public function desactivateBankAccount($UserId)
    {
        $BankAccount = new MangoPay\BankAccount();
        $BankAccount->Active = false;
        $this->api->Users->UpdateBankAccount($UserId, $BankAccount);
    }

This code does not work at all why?

Does anyone have a code sample?

Thank you for help.

**Comment by iammichiel** [comment]
This code should work : 

```php
$api->Users->UpdateBankAccount($UserId, $BankAccount);
```

However, you have to previously get the BankAccount object form the API, set the `Active` flag to `false` and perform the update. 

```php
$bankAccount = $api->Users->GetBankAccount($userId, $bankAccountId);
$bankAccount->Active = false;
$api->Users->UpdateBankAccount($userId, $bankAccount);
```

**Comment by paulhristea** [comment]
Hi @ChristopherTRIERWEILER!

Have you been able to solve this issue? The general idea is that whenever we want to update an entity using the SDK  PUT methods, we have to first retrieve that specific entity from the API using one of the GET methods.

If you still encounter difficulty when trying it this way, please get back to us with more details. Otherwise, please let us know as well.
Thanks!
