### ISSUE TITLE
Omnipay integration ?

### ISSUE THREAD

**Issue by lucasmichot** [Mangopay/mangopay2-php-sdk#25]
Hi, thanks for this useful package.
Do you plan to create a gateway for Omnipay package ?
https://github.com/thephpleague/omnipay

**Comment by garak** [comment]
:+1:

**Comment by shakaran** [comment]
I would like have OmniPay integration too if possible. Any progress with this issue?

**Comment by lucasmichot** [comment]
I don't think it will once be done, so why we've changed to another payment provider.

**Comment by shakaran** [comment]
oh sorry to heard that @lucasmichot but It is pretty understable if MangoPay don't implement the feature request demanded by his users. Could I know which provider did you use instead? (just in case that MangoPay don't speed up his develoment on this)

**Comment by hobailey** [comment]
Hey everyone, sorry for the radio silence. We have discussed the possibility of an Omnipay integration a couple of times and since it's not a perfect fit, we haven't yet taken action - we're about wallets and 3rd party payments, whereas most (all?) Omnipay integrations are straightforward ecommerce payments, and hence they don't have the complexity that we have (of putting money into a wallet, transferring to another wallet, doing a payout, validating KYC when the limits are passed etc).
I'll keep the subject open, but I can't promise a move on this in the short-term I'm afraid.

**Comment by hobailey** [comment]
Having reviewed this again, as warned in my last post, this is not something we feel is a good if at this time - we may well review that later in the year, but for now we unfortunately have other priorities to focus on :-/
