### ISSUE TITLE
Severity: error --> Exception: Call to undefined function MangoPay\Libraries\curl_init(

### ISSUE THREAD

**Issue by AlexBrend** [Mangopay/mangopay2-php-sdk#366]
Hello,

I am using payin functionality of mangopay by cron job. When cron runs that time i make a payin call but i am alsways getting below error.

Severity: error --> Exception: Call to undefined function MangoPay\Libraries\curl_init() /var/www/public/dev.myservicemenu.com/public_html/application/third_party/mangopay/MangoPay/Libraries/HttpCurl.php  Line:38 

Whenever i manually call cron jobs it is working properly.
I need to solve this issue as soon as possible as my site is live and we have implemented this feature. Please reply fast on this issue.
Thanks in advance.

**Comment by Riwak** [comment]
Hello @AlexBrend,

I don't think that this issue is strictly related to MANGOPAY SDK as it occurs only when you are calling the method from a cron-job 🙂 

Anyway, does you cronjob load the right configuration file? Can you please check?
Usually, cron-job use different php.ini / user session to do their job.

Hope it will help you, have a nice day,

Audouin,
