### ISSUE TITLE
throw new \MangoPay\Exception('Cannot create or write to file ' ).

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#38]
i create the tmp folder and set permission also but still it gives the mention error while i create the new natural user : anybody have solutions?

**Comment by hobailey** [comment]
Hi @ananrola, could you show us the relevant bit of code (obviously without your passphrase or clientid)? If you're getting a permissions error, there is either something still wrong with the permissions or something with the server config. The whole tmp folder needs to have ready/write permissions so that the script can add/overwrite and execute any file within.

**Comment by ananarola** [comment]
thanks for reply @hobailey . I solve error . I mistaken to pass clientid thats why the issue raise. now solve it
