### ISSUE TITLE
MangoPay\Exception Message: Cannot put token to file

### ISSUE THREAD

**Issue by ananarola** [MangoPay/mangopay2-php-sdk#45]
I am getting this error while i shift my code to liive server

**Comment by ananarola** [comment]
Please reply fast i need to upload app

**Comment by hobailey** [comment]
If you check the SDK for this exception (https://github.com/MangoPay/mangopay2-php-sdk/blob/1be22982a5b89278151f3fba0880333429f9a23f/MangoPaySDK/tools/defaultStorageStrategy.inc#L47) you'll see that its because the SDK is unable to write the file. The most likely reason for this is that you have not set the necessary write permissions for your TemporaryFolder (that you set in the API config)

**Comment by Manu2V** [comment]
Hello,

Thans for your help, i have this problem on mangopay but i don't understand how i can resolve it in the code ?

        $serialized = serialize($token);
        $result = file_put_contents($this->GetPathToFile(), $this->_prefixContent . $serialized, LOCK_EX);
        if ($result === false)
            throw new \MangoPay\Libraries\Exception('Cannot put token to file');

On my web site, sometimes it works sometimes the message "MangoPay\Exception Message: Cannot put token to file" appears and don't permit the payment.

Can you help me please,

Manu
