### ISSUE TITLE
Updating Already added bank details causing the account to be inactive

### ISSUE THREAD

**Issue by piyushfreeads** [Mangopay/mangopay2-php-sdk#512]
When a user has added a bank account in mango pay it may so happen that there could be some typing mistake with name etc. So we are allowing user tp edit the bank details. We are using PHP SDK and when using the UpdateBankAccount function of the users object it is not updating the details rather making the bank account active does that mean we cannot update the bank details once added or this is a BUG. The Active attribute of bank object can only be set to False. if set o true will end up in error.

**Comment by H4wKs** [comment]
Hi @piyushfreeads,
I would double check with MangoPay support, but from my understanding, you can't update a bank account object, and this is not a limitation of the PHP SDK. 
According to the MangoPay API Doc, ( https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e24_the-bankaccount-object ) you can only create, list, view, desactivate a bank account object.
The problem here is that the PHP SDK method name `UpdateBankAccount` is miss leading, because what this method do is calling the bank account desactivate URL ( https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e306_deactivate-a-bank-account ). We have the same issue when it's come to registered cards.

**Comment by fredericdelordm** [comment]
Hello @piyushfreeads,

You can't update a bankAccount. You need to deactivate the old one and submit a new one with the new data.

hello @H4wKs, thank you for the feedback. We will update it soon.

**Comment by piyushfreeads** [comment]
Thanks for update.
