### ISSUE TITLE
Error registration data but it's a good format 

### ISSUE THREAD

**Issue by Geoffray-buhler** [Mangopay/mangopay2-php-sdk#513]
When i send my registration data to update Registration data on mangopay server i have this response :
![image](https://user-images.githubusercontent.com/55780756/126620667-2b9199a2-73b3-487d-be12-d48a59fd6e65.png)

so i see my format of Registration data is not good but in mangopay documentations : https://docs.mangopay.com/endpoints/v2.01/cards#e1042_post-card-info

there is a exemple of format :
![image](https://user-images.githubusercontent.com/55780756/126621351-f5183f06-416c-4902-bf4d-3bddf85fcb27.png)

and i send this : 
![image](https://user-images.githubusercontent.com/55780756/126621432-8534c198-0567-447e-805a-bb4202aea67a.png)

So i don't understand where is the problem with my registration data format

**Comment by H4wKs** [comment]
Hi @Geoffray-buhler,
I am not 100% sure of the problem, but I believe you submit for the RegistrationData a Json array object that look like this:
{
"RegistrationData" : "data=EFOIJZfzeOfjzeR3ZIEFJdsFIEJFEOIFJzeFIJZEFZ....",
}
While you should submit a string that look like this "data=EFOIJZfzeOfjzeR3ZIEFJdsFIEJFEOIFJzeFIJZEFZ...."
So you want to have this:
```php
$cardRegister->RegistrationData = "data=EFOIJZfzeOfjzeR3ZIEFJdsFIEJFEOIFJzeFIJZEFZ...."
```
instead of
```php
$cardRegister->RegistrationData = "{
"RegistrationData" : "data=EFOIJZfzeOfjzeR3ZIEFJdsFIEJFEOIFJzeFIJZEFZ....",
}"
```
If you want / can share the code, that would be more easy to spot the problem unless this message help you catch / fix the issue.

**Comment by Geoffray-buhler** [comment]
You are right it will be necessary to change the format of the string, I put the code if it can help someone ^^
```php
if (isset($_GET['data'])) {
            $CardRegistration = $session->get('CardRegistration');
            $CardRegistration->Id = $session->get('PreRegistrationId');
            $CardRegistration->RegistrationData = 'data='.$_GET['data'];
```

and the result : 
![succes](https://user-images.githubusercontent.com/55780756/127117962-edd561e6-54c7-47ac-8605-07e8c91c3634.png)

thank you once again ^^
