### ISSUE TITLE
Bad PSR-4

### ISSUE THREAD

**Issue by euskadi31** [MangoPay/mangopay2-php-sdk#52]
Hello,

Thank you for your response to my previous issue, however there are still some problems.

Please follow PSR-2 (Coding Style Guide)
see: http://www.php-fig.org/psr/psr-2/

Use Psr\Logger (PSR-3) for MangoPay\Libraries\Logs
see: https://github.com/php-fig/log

**Comment by hobailey** [comment]
PSR-4 and PSR-2/3 are different things :-) So its normal that a PSR-4 compliant library may not meet the other specifications etc. If you have specific problems with the newly released version and PSR-4 in particular, then please let us know, but otherwise it's not "bad" :-)
As for PSR-2 and 3, this is not something we're currently working on, but we may well do in the future.
