### ISSUE TITLE
Call to a member function IsExpired() on a non-object	

### ISSUE THREAD

**Issue by jaysukhnm** [Mangopay/mangopay2-php-sdk#61]
Hello, 

I am using mangopay since march-2015, it's works fine, now days i found fatal error while register new user, 

Error: Call to a member function IsExpired() on a non-object	
File: /var/www/vhosts/xxx.com/Vendor/mangopay2-php-sdk-master/MangoPaySDK/tools/authorizationTokenManager.inc	
Line: 33

please help me to fix this issue,

thanks

**Comment by hobailey** [comment]
Hmm, sounds strange - have you recently updated your SDK? And does it happen with lots of different API calls? Either way, I'd suggest updating to the latest version of the SDK to ensure you have the most stable version :-)

**Comment by aslafy-z** [comment]
Same for me, but with php ~5.6 since yesterday :
Error: MangoPay\Libraries\AuthorizationTokenManager::GetToken(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "MangoPay\OAuthToken" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

There was also a problem to call the logger, i had to fix the path (https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/Configuration.php#L49) to: Mangopay/Libraries/Logs..

**Comment by hobailey** [comment]
Hmm, how strange - thanks @aslafy-z for flagging this up too and for the logs fix - I've just updated that.

To you both, try deleting your temporary oauth file and see if that helps?

**Comment by jaysukhnm** [comment]
@hobailey , thanks for your reply, I have not update sdk since beginning, and few minutes ago i have try with latest sdk, still issue is same.

**Comment by jaysukhnm** [comment]
Can you please give path for "try deleting your temporary oauth file "?

**Comment by hobailey** [comment]
I think this bug comes from a recent update to meet PSR-4 standards (https://github.com/Mangopay/mangopay2-php-sdk/commit/4c1514fe8ee4f03d3225d76c8c85ccceb0576829) and the oauth file changed its format. The location of the file is whatever you set in your config when initialising the API - for example: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/demos/users_all.php#L11

**Comment by jaysukhnm** [comment]
Strange it's work for me, I have delete temp file. 
i have use mangopay in my cron function, so i can't identify if same problem occures in future.
can you please give solution other then deleting temp file each time, or reason why should i delete temp periodically?

**Comment by hobailey** [comment]
It should only happen once after the update following that commit - if you're worried though, you should always catch errors (like in the example script included in my previous comment) and then you can handle any problems (but as I say, it shouldn't happen again :-) )

**Comment by aslafy-z** [comment]
As i said, i'm using AppVentus/MangopayBundle who set the TemporaryFolder to "sys_get_temp_dir()" (=/tmp).
I just empty the folder and mangopay's file is not regenerated and the error is still there :(

**Comment by hobailey** [comment]
OK, and when did you last update your package?

**Comment by aslafy-z** [comment]
Yesturday (not working anymore) and the day before (working at this time - the day before yesturday).

**Comment by hobailey** [comment]
Hmm, I did really get that I'm afraid - if you do a fresh install of the latest SDK, delete the temporary file and then do an API call, it should work (or at least, it has in all the cases where this bug has happened).
