### ISSUE TITLE
Prevent registration of same credit card

### ISSUE THREAD

**Issue by enderakgul** [Mangopay/mangopay2-php-sdk#65]
How can i prevent registration of same credit card by same user again and again

**Comment by hobailey** [comment]
Hi @enderakgul, there is no particular API function to achieve this, but I suggest you view the list of a cards for the user, and check against the alias and expiry date fields and if you find a match, then you could pass the card you just added to inactive and show an error to the user that there is a duplicate.

Unfortunately this is only possible retroactively (so that you know the alias) and also it's not perfect since the alias field is not unique to one card, but it's the best possible method of achieving what you wish.
