### ISSUE TITLE
How to remove users?

### ISSUE THREAD

**Issue by akfaisel** [Mangopay/mangopay2-php-sdk#75]
Hi,

How do I remove users (legal or natural) from dashboard?

**Comment by hobailey** [comment]
Hi @akfaisel, if you wish to delete users, there is no such functionality I'm afraid.

**Comment by Fab1en** [comment]
I have a MangoPay sandbox account that I use for testing. My application is not ready yet, so I run batch tests that create fake users in my account.
What you say is that there are no ways to remove them after testing ?

**Comment by hobailey** [comment]
That is right. Our API does not allow you to delete any resources, just create, edit and view. If you wish to "start a fresh" then I suggest you create a new sandbox account: https://www.mangopay.com/signup/create-sandbox/

**Comment by DavidGarciaCat** [comment]
Are you offering any way to remove a Sandbox account for security/legal reasons?

**Comment by hobailey** [comment]
@DavidGarciaCat - there is no way to delete an account either I'm afraid.

**Comment by DavidGarciaCat** [comment]
OK - That is a security issue in case of `dev`/`uat` users are testing an app, adding real details. Can you discuss with the tech team a secure way to remove a sandbox account please?

**Comment by poncianodiego** [comment]
Hello,

I think you should be able to delete sandbox users. For our app we created a lot of test users and would like to start fresh.

Thanks

**Comment by daveyx** [comment]
here too, i want to delete my testusers too!

please give access to that functionality

**Comment by peterrisdon1** [comment]
You will run into regulatory issues if users cannot be deleted, plus all the Security problems this creates.

**Comment by jontelm** [comment]
Anything new on this one?

**Comment by DavidGarciaCat** [comment]
Hey @jontelm 

I would be surprised if MangoPay has - at least - planned this in a short term period. This issue was opened on Dec 2015 and closed on 15 Apr 2016, I think this "shows" the interest on this feature, unless there's a public roadmap that we can check (and I didn't see it).

I am still waiting for this, I have several test accounts that should be removed, but I'm unable to do it...

**Comment by jontelm** [comment]
@DavidGarciaCat https://trello.com/b/y3UFMThq/mangopay-public-roadmap

**Comment by iammichiel** [comment]
What is actually really fun here is that since there is feature to delete data from Mangopay, their database is growing at exponential speed. And thus causing huge performance issues. 

This all leads to decision like the one announced last week. Limiting the events API to 45 days of history. Great story, limiting functionnality because of bad technical decisions...

**Comment by peterrisdon1** [comment]
Hahahhahha!

Regards

**Comment by DavidGarciaCat** [comment]
That's obviously a bad tech decision, and should not be done.

I understand that some limits could be applied when we need to deal with a lot of data (like when we create reports) but honestly, some sort of added service like Redis jobs could make our lives easier, just adding a single request to get *all* transactions for a user who has more than 100.000 transfers in their wallet (just an example) instead of force me to create 12 reports (one for each month) and then waste time merging all exported files in a single file to be able to track everything for review and reconciliation.

Apply limits - although is good for some cases - is not the only way to work, and obviously not the best way to provide a good service...

**Comment by jontelm** [comment]
From Tech support
```
Hi Jonatan,

At the moment there are no plans to allow the ability to delete data from the sandbox account.
What I would suggest, if you need a clean environment, is to create a new account.
This will allow you to have a clear environment to test in.

Regards,
```

**Comment by DavidGarciaCat** [comment]
Same answer I got more than 1 and a half year ago https://github.com/Mangopay/mangopay2-php-sdk/issues/75#issuecomment-187153934

👎

**Comment by lihanyu23** [comment]
This sounds too weird, a sandbox is a playground, you want to create and delete thing until you got the right things. Why should I create an account for fresh start every time.

**Comment by Nicolas-Bouteille** [comment]
+1 for this! I totally share hanyu-natsu's point of view.

**Comment by DavidGarciaCat** [comment]
Although every time there are more devs asking for this, what I got from my account manager was:

> You probably know we can't delete any data from our databases due to legal restrictions (these informations can be asked anytime by the police to fight against money laundering for example).
Our sandbox env. is a copy of our production env., especially in terms of features. We do not want to make an exception for data deletion in Sandbox env. only for the moment, and the answer our Tech Support brought to all of you will not change in the near future. That is clearly a choice we  have made.
Today, you can ask our Tech Support to disactivate your sandbox account, and create as many other sandbox accounts as needed, but no deletion.


So, their position on this is ”I’ll give you the finger” because even with the new GDPR no one has the intention to apply something that regulations demand.

**Comment by MoogyG** [comment]
> This sounds too weird, a sandbox is a playground, you want to create and delete thing until you got the right things. Why should I create an account for fresh start every time.

+1 for this!

**Comment by Lucyfire** [comment]
Is there any update on this?

**Comment by DavidGarciaCat** [comment]
no one cares…

**Comment by ShooterArk** [comment]
Thats just so stupid :/ .. Sandbox is for testing purpose. I can understand if they want to block the delete mechanism in Production accounts but on Sandbox it should be allowed. Now I am facing the same issue. Created a bunch of testing accounts and now cant delete them..

**Comment by AaronAntonopoulos** [comment]
any update on this?
Facing the same problem...

**Comment by DavidGarciaCat** [comment]
@AaronAntonopoulos no one has added any other reply announcing it, so again "no one cares"

I understand that for legal reasons there are some records that cannot be deleted on production, but sandbox is - as per its own name says - a sandbox, and `user acceptance` users can provide real data that might lead to a problem if there's a security breach.

I just decided not to use MangoPay for any project due to the lack of consistency with the GDPR requirements. And I am still considering my options to know what kind of measures I should take due to all the (personal) details stored during testing purposes that I am completely unable to delete.

Note: even on production, MangoPay could (not to say should) provide a DELETE endpoint to "delete the sensitive data" instead of ask for an update, and at the same time that account should be flagged as deactivated. Something that I am 100% sure they already have (based on other replies) but they just don't want to post on their API Docs.

**Comment by williamdes** [comment]
cc @mickaelpois

**Comment by oussama-kh** [comment]
any update on this ?

**Comment by DavidGarciaCat** [comment]
Forget it. Even noticing the number of requests won't happen, no one has made any step forward... Shame...

**Comment by quaidesbalises** [comment]
Same here ... that is a crazy discussion for a standard API sandbox usecase

**Comment by fredericdelordm** [comment]
Hello @quaidesbalises, @DavidGarciaCat, @oussama-kh,

Regarding sandbox environnement, if you want to start fresh, just create a new sandbox in the MANGOPAY hub (https://hub.mangopay.com). It's unlimited.

For the ability to delete a user in production, let me double check why it's not possible.

**Comment by vibonacci** [comment]
Interesting that you are not able to delete Sandbox API keys as well. So even the suggestion to create a new Sandbox key for a 'fresh' start, isn't really a fresh start! You will still be confused as to which Sandbox key you've created last and want to use.

I'm really curious to the reasoning of why this is not implemented.

**Comment by DavidGarciaCat** [comment]
The reason is to avoid building a sandbox platform that is not the same than a production platform.

The main benefit of using MangoPay is each user has it's own wallet, and the required KYC process. It's very interesting and provides a nice security mechanism, but it causes several problems on the sandbox.

Stripe allows deleting all the users and payments from the list (or at least they hide the data from you, so it's not bothering anyone). Another point is if this is a solution that works for you.

**Comment by williamdes** [comment]
The version https://github.com/Mangopay/mangopay2-php-sdk/releases/tag/3.37.0 allows to close user accounts. Not yet delete them. 
I guess that's better than nothing 

https://docs.mangopay.com/api-reference/users/close-natural-user
