### ISSUE TITLE
500 when retrieving SecureModeRedirectURL

### ISSUE THREAD

**Issue by umbecanessa** [Mangopay/mangopay2-php-sdk#81]
Hey, i've a super annoying error when i'm trying to access to SecureModeRedirectURL of the CardPreAuthorization object.

Every time i Get : 

\MangoPay\ResponseException: Code: 500
Message: Internal server error. Internal Server Error

Details: MangoPay\Libraries\Error Object ( [Message] => Internal Server Error [Errors] => )

even if I try to print it with. Is the only property in the object that create this error.

Here is my code:

````
$CardPreAuthorization = new \MangoPay\CardPreAuthorization();
    $CardPreAuthorization->AuthorId = $updatedCardRegister->UserId;
    $CardPreAuthorization->DebitedFunds = new \MangoPay\Money();
    $CardPreAuthorization->DebitedFunds->Currency = "EUR";
    $CardPreAuthorization->DebitedFunds->Amount = $_SESSION['amount']*100;
    $CardPreAuthorization->SecureMode = "DEFAULT";
    $CardPreAuthorization->CardId = $card->Id;
    $CardPreAuthorization->SecureModeReturnURL = "https://mywebsite/index.php";
      
    $CreatePreAuthorization = $mangoPayApi->CardPreAuthorizations->Create($CardPreAuthorization);
   echo $CreatePreAuthorization->SecureModeRedirectURL;
```

**Comment by hobailey** [comment]
Hi @umbecanessa, I'm confused why you think that just accessing the `SecureModeRedirectURL` is triggering the API error 500? But a couple of things:
* With `SecureMode` set to "DEFAULT", you'll only get a `SecureModeRedirectURL` above certain amounts (otherwise it will be null). But either way, you should check the `SecureModeNeeded` parameter (if you're not already) to know whether you need to make use of the `SecureModeRedirectURL` or not
* I've just run your code (with different Amount, UserId and CardId of course) and it works fine (as I say, I wouldn't expect an error 500 for the code as you have it)
* An error 500 from the API would be causing by the request you sent, therefore whatever you do with the response (access various variables etc) wouldn't trigger an error 500

**Comment by umbecanessa** [comment]
Hi @hobailey, is very strange I just try it (without changing any line of code) now and it works perfectly.

**Comment by hobailey** [comment]
OK, thanks for the update :-)
