### ISSUE TITLE
Transactions with rollbacking

### ISSUE THREAD

**Issue by aistis-** [Mangopay/mangopay2-php-sdk#89]
Hello. Is it possible to Have payments transaction with possibility of rollbacks?

We have a case where we are splitting payments to multiple wallets, but in case of an error (network or whatever) we would love to have a rollback of these payments and even new wallets creation.

Do you have anything to suggest?

**Comment by hobailey** [comment]
Hey there,
I'm not quite sure what you mean by "rollback" (or at least, what the exact use case is), but I would suggest either doing refunds for these transactions, or if it's more a problem of finding a solution for network connectivity issues, then using an `Idempotency-Key` in your request header would be perfect (so that you can safely replay the call several times in 24 hours, and each call with the same  `Idempotency-Key` will only be accepted once): https://docs.mangopay.com/api-references/idempotency-support

**Comment by aistis-** [comment]
Thank you for pointing out `Idempotency` support. I do not want to dive into the details of the case, but the feature I am looking for would be the same as any database transaction (like: `begin`, `commit` and `rollback` commands), but on the API level. Anyway, if you do not support it, we will find a better way to handle our internal errors.

**Comment by hobailey** [comment]
OK, well let us know if you have any further questions - it sounds like the Idempotency support could be a good way to start in any case.
